server:
  port: 9003

spring:
  application:
    name: Eureka-Server03

eureka:
  instance:
    hostname: eureka03
  server:
    enable-self-preservation: false  #自我保护机制关闭
  client:
    register-with-eureka: false   #自身不注册
    fetch-registry: false         #是否从Eureka服务端获取服务信息
    serviceUrl:
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/     单节点


