server:
  port: 9007


spring:
  application:
    name: Consumer01
eureka:
  client:
    register-with-eureka: false   #自身不注册
#    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

