server:
  port: 9009


spring:
  application:
    name: Consumer02
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
eureka:
  client:
    register-with-eureka: false   #自身不注册
#    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
#官方的配置
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: fals